# Generated by Django 5.0.3 on 2024-05-13 13:20

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficiaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_et_prenom', models.CharField(max_length=255, verbose_name='Nom et prénom')),
                ('date_naissance', models.DateField(verbose_name='Date de naissance')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Bénéficiaire',
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime.today, verbose_name='Date')),
                ('destination', models.CharField(max_length=255, verbose_name='Destination')),
                ('compagnie', models.CharField(choices=[('Tunisair', 'Tunisair'), ('Tunisair Express', 'Tunisair Express')], default='Tunisair', max_length=20, verbose_name='Compagnie')),
                ('vous', models.BooleanField(default=False, verbose_name='Est-ce que le bénéficiaire est vous-même ?')),
                ('retraité', models.BooleanField(default=False, verbose_name='Est-ce que le demandeur est retraité ?')),
                ('statut', models.CharField(choices=[('Accepté', 'Accepté'), ('Refusé', 'Refusé'), ('En attente', 'En attente')], default='En attente', max_length=20, verbose_name='En attente')),
                ('is_approved', models.BooleanField(default=False, verbose_name='Est approuvé')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('beneficiaires', models.ManyToManyField(blank=True, default='sans bénéficiaire', to='ticket.beneficiaire', verbose_name='Beneficiaires')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ticket',
                'verbose_name_plural': 'Tickets',
                'ordering': ['date'],
            },
        ),
    ]
