# Generated by Django 5.1.7 on 2025-07-31 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0002_ticket_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='ai_analysis_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name="Date d'analyse IA"),
        ),
        migrations.AddField(
            model_name='ticket',
            name='ai_category',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Catégorie IA'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='ai_category_confidence',
            field=models.FloatField(default=0.0, verbose_name='Confiance catégorie IA'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='ai_priority',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Priorité IA'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='ai_priority_reason',
            field=models.TextField(blank=True, null=True, verbose_name='Raison de la priorité IA'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='ai_priority_score',
            field=models.FloatField(default=0.0, verbose_name='Score de priorité IA'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='ai_sentiment',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Sentiment IA'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='ai_sentiment_score',
            field=models.FloatField(default=0.0, verbose_name='Score sentiment IA'),
        ),
    ]
