# Generated by Django 5.1.7 on 2025-08-05 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0003_ticket_ai_analysis_date_ticket_ai_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='responded_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de réponse'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='response_time_days',
            field=models.FloatField(blank=True, null=True, verbose_name='Temps de réponse (jours)'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='response_time_hours',
            field=models.FloatField(blank=True, null=True, verbose_name='Temps de réponse (heures)'),
        ),
    ]
