# Generated by Django 5.0.3 on 2024-05-11 18:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startdate', models.DateField(help_text='Votre congé du ..', null=True, verbose_name='Date début')),
                ('enddate', models.DateField(help_text='et fini à...', null=True, verbose_name=' Date fin ')),
                ('leavetype', models.CharField(choices=[('congé', 'congé annuel'), ('accident de travail', 'accident de travail'), ('maladie', 'maladie'), ('mission', 'mission'), ('absence', 'absence')], default='Congé annuel', max_length=25, null=True, verbose_name=' type congé ')),
                ('status', models.CharField(default='pending', max_length=12)),
                ('is_approved', models.BooleanField(default=False)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Leave',
                'verbose_name_plural': 'Leaves',
                'ordering': ['-created'],
            },
        ),
    ]
