# Generated by Django 5.1.7 on 2025-07-31 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='ai_analysis_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name="Date d'analyse IA"),
        ),
        migrations.AddField(
            model_name='leave',
            name='ai_approval_factors',
            field=models.TextField(blank=True, null=True, verbose_name="Facteurs d'approbation IA"),
        ),
        migrations.AddField(
            model_name='leave',
            name='ai_approval_probability',
            field=models.FloatField(default=0.0, verbose_name="Probabilité d'approbation IA"),
        ),
        migrations.AddField(
            model_name='leave',
            name='ai_priority',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Priorité IA'),
        ),
        migrations.AddField(
            model_name='leave',
            name='ai_priority_score',
            field=models.FloatField(default=0.0, verbose_name='Score de priorité IA'),
        ),
    ]
