# Generated by Django 5.1.7 on 2025-08-02 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0002_leave_ai_analysis_date_leave_ai_approval_factors_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='leavetype',
            field=models.CharField(choices=[('congé', 'congé annuel'), ('accident de travail', 'accident de travail'), ('maladie', 'maladie'), ('mission', 'mission'), ('absence', 'absence')], default='congé', max_length=25, null=True, verbose_name=' type congé '),
        ),
    ]
