# Generated by Django 5.1.7 on 2025-08-05 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0003_alter_leave_leavetype'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='responded_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de réponse'),
        ),
        migrations.AddField(
            model_name='leave',
            name='response_time_days',
            field=models.FloatField(blank=True, null=True, verbose_name='Temps de réponse (jours)'),
        ),
        migrations.AddField(
            model_name='leave',
            name='response_time_hours',
            field=models.FloatField(blank=True, null=True, verbose_name='Temps de réponse (heures)'),
        ),
    ]
